(() => {
  'use strict';

  function create(options = {}) {
    const defaultFrequencyBands = options.defaultFrequencyBands || Object.freeze({ floor: 25, lowMid: 180, midHigh: 2400, ceiling: 12000 });
    const now = options.now || (() => performance.now());

    return {
    center: { x: -0.16, y: 0.0 },
    interfaceMode: 'basic',
    fractalType: 0,
    visualStyle: 0,
    zoom: 1,
    iterations: 220,
    flow: 0.28,
    motion: 0.85,
    fractalDimensional: false,
    fractalTilt: .45,
    fractalDepthSpeed: .32,
    fractalPerspective: .45,
    fractalSlice: .25,
    fractalLighting: .55,
    fractalAudioDepth: .4,
    equationFolding: false,
    equationFold: .18,
    equationWarp: .12,
    equationFoldMotion: .16,
    equationFoldOffset: .1,
    equationWarpScale: .45,
    equationFoldAudio: .25,
    coreCStrength: .5,
    coreBiasReal: 0,
    coreBiasImag: 0,
    barWidth: 1,
    barGlow: 1,
    barReflection: .35,
    barMotion: .35,
    barEcho: .6,
    barGrid: 1,
    barStyle: 0,
    radialSize: 1,
    radialGlow: 1,
    radialWaves: 1,
    radialTwist: .3,
    radialSpokes: 1,
    radialAtmosphere: 1,
    pulseDensity: .75,
    pulseSize: 1,
    pulseCooldown: 1,
    pulseJagged: 1,
    pulseTrail: 1,
    pulseDetail: 1.25,
    bulbPower: 4,
    bulbDetail: .55,
    bulbAudio: .65,
    bulbOrbit: .28,
    bulbFold: 0,
    bulbGlow: 1.2,
    bulbCamera: 3.75,
    bulbYaw: .38,
    bulbPitch: .12,
    pulseEvents: [],
    pulsePreviousLevels: [0, 0, 0],
    pulseLastLevels: [0, 0, 0],
    pulseArmed: [true, true, true],
    pulseCooldowns: [0, 0, 0],
    pulseGlobalCooldown: 0,
    pulseAcceptedTotal: 0,
    spin: 0.18,
    spin: 0.18,
    modulationRotationPhase: 0,
    equation: 0.09,
    visualTime: 0,
    adaptiveQuality: true,
    performanceScale: 1,
    frameTime: 16.7,
    palette: 0,
    reactivity: 0.9,
    autoReactivity: true,
    autoReactivityGain: 1,
    autoReactivityTarget: 0.74,
    musicPersonality: 'balanced',
    songDirectorEnabled: false,
    songDirectorStyle: 'cinematic',
    songDirectorBehavior: 'auto',
    songDirectorTransition: 'auto',
    songDirectorIntensity: .55,
    songDirectorValues: {},
    analysisBassGain: 1,
    analysisMidGain: 1,
    analysisHighGain: 1,
    frequencyBandMode: 'basic',
    frequencyFloor: defaultFrequencyBands.floor,
    lowMidSplit: defaultFrequencyBands.lowMid,
    midHighSplit: defaultFrequencyBands.midHigh,
    frequencyCeiling: defaultFrequencyBands.ceiling,
    spectrumData: new Float32Array(64),
    waveformData: new Float32Array(64),
    bass: 0,
    mids: 0,
    highs: 0,
    rms: 0,
    beat: 0,
    musicClockBass: 0,
    musicClockMids: 0,
    musicClockHighs: 0,
    musicClockRms: 0,
    musicClockBeat: 0,
    musicClockPreviousBass: 0,
    musicClockPreviousMids: 0,
    musicClockPreviousHighs: 0,
    musicClockPreviousRms: 0,
    musicClockPreviousBeat: 0,
    equationBass: 0,
    equationMids: 0,
    equationHighs: 0,
    equationBeat: 0,
    musicMotionBass: 0,
    musicMotionMids: 0,
    musicMotionHighs: 0,
    musicMotionBeat: 0,
    musicBaselineBass: 0,
    musicBaselineMids: 0,
    musicBaselineHighs: 0,
    equationSmoothing: .9,
    beatAverage: 0.05,
    beatFastEnvelope: 0,
    beatSlowEnvelope: 0,
    beatOnsetAverage: .008,
    beatCooldownRemaining: 0,
    beatSensitivity: .65,
    beatCooldownMs: 150,
    beatDetectedTotal: 0,
    beatDetectorArmed: true,
    autoBpm: true,
    manualBpm: 120,
    detectedBpm: 120,
    bpmConfidence: 0,
    beatOffsetMs: 0,
    beatGridAnchor: now() / 1000,
    detectedBeatTimes: [],
    beatGridIndex: -1,
    beatGridPhase: 0,
    showSequence: [],
    showPlaying: false,
    showIndex: -1,
    showLoop: true,
    showShuffle: false,
    showEntryStartTime: 0,
    showEntryStartBeat: 0,
    showTransitioning: false,
    showTransitionBlack: false,
    operatorMode: false,
    performanceBlackout: false,
    monitorVolume: 0.82,
    monitorMuted: false,
    analysisSmoothing: 0.8,
    frequencyColorEnabled: true,
    frequencyColorAmount: 0.55,
    frequencyHue: 0,
    dominantBand: 'silence',
    loopBeforeExport: false,
    exporting: false,
    exportWidth: 1920,
    exportHeight: 1080,
    exportDetail: 1.6,
    exportIterations: 600,
    exportIterationTarget: 0,
    exportMatchLive: true,
    exportSamplingMode: 'standard',
    exportSupersampling: false,
    offlineSamplePass: 0,
    exportSampleOffsetX: 0,
    exportSampleOffsetY: 0,
    offlineBaseModulation: null,
    autoDrift: true,
    beatPulse: true,
    drag: null,
    lastFrame: performance.now(),
    audioName: '',
    playlist: [],
    playlistIndex: -1,
    playlistLoadedId: null,
    playlistId: 0,
    audioMode: 'deck',
    liveAudioLabel: '',
    obsChromaKey: false,
    obsChromaThreshold: .08,
    modulationEnabled: true,
    modulationMappings: [],
    modulationValues: {},
    cameraMotionPreset: 'off',
    cameraPath: null,
    performanceMode: 'auto',
    bulbLiveBudget: .88,
    unleashedMode: false,
    hardwareInfo: null,
    hardwareRecommendation: 'balanced',
    offlineExporting: false,
    offlineHdrExport: false,
    offlineTenBitExport: false,
    offlineFps: 60,
    nowPlayingEnabled: false,
    nowPlayingTitle: '',
    nowPlayingArtist: 'Tempest Mainframe',
    nowPlayingPosition: 'bottom-left',
    customColors: [
      [9 / 255, 17 / 255, 37 / 255],
      [32 / 255, 70 / 255, 110 / 255],
      [99 / 255, 85 / 255, 142 / 255],
      [107 / 255, 168 / 255, 181 / 255]
    ],
    lastUiUpdate: 0
  };
  }

  window.QuarticAppState = Object.freeze({ create });
})();
